name: InvenSave
version: '1.0'
main: kr.eme.invensave.InvenSave
api-version: '1.20'
author: Dev_Eme
description: KeepInventory Plguin
commands:
  인벤세이브:
    description: InvenSave Plugin Command
    usage: /<command>
    aliases: invensave